=== anthoniraj/WebServices/XML Basics/XML Schema/university.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence maxOccurs="3">
                <xs:element name="student">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="semester">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Winter"/>
                                        <xs:enumeration value="Fall"/>
                                        <xs:enumeration value="Summer"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>     
                            <xs:element name="course" type="xs:string" />                       
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="20" />
                                        <xs:maxInclusive value="24" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="doj" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anthoniraj/WebServices/XML Basics/XML Schema/university.xml
<?xml version="1.0"?>
<university   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="university.xsd">
    <student>
        <name>Kumar</name>
        <semester>Fall</semester>
        <course>M.Tech</course>
        <age>22</age>  
        <doj>2013-03-23</doj>        
    </student>
    <student>
        <name>Kumar</name>
        <semester>Fall</semester>
        <course>B.Tech</course>
        <age>23</age>  
        <doj>2011-01-21</doj> 		
    </student>
    <student>
        <name>Balaji</name>
        <semester>Summer</semester>
        <course>B.Tech</course>
        <age>21</age>  
        <doj>2012-02-11</doj> 		
    </student>
</university>
